export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS";
export const ADD_USER_DETAILS = "ADD_USER_DETAILS";

export const SET_GATEWAY_URL = "SET_GATEWAY_URL";

export const ORDER_LOADING = "ORDER_LOADING";
export const LOAD_ORDER = "LOAD_ORDER";
